#!/usr/bin/env bash
# Challenge Script

calculate_factor_product()
{
	if [ $# -ne 3 ]; then
		local arguments=("$@")
		local counter=0
		local factor_product=1
		for argument in "${arguments[@]}"; do
			if [ $counter -gt 1 ]; then
				factor_product=$(echo "$argument * $factor_product" | bc)
			fi
			counter=$((counter + 1))
		done
	else
		factor_product=$3
	fi

	local first_factor=$2
	local equation=$(echo "$1" | tr ':' '=')

	local comparison_result=$(echo "if($factor_product > $first_factor) 1 else 0" | bc)
	if ((comparison_result == 1)); then
		local temporary=$first_factor
		first_factor=$factor_product
		factor_product=$temporary
	fi

	echo "$equation$first_factor*$factor_product"
}

if [ $# -ne 1 ]; then
	echo 'Usage: rsa <file>'
	exit 1
else
	while read -r number; do
		factorization_result=$(factor "$number")
		calculate_factor_product $factorization_result
	done < "$1"
fi

